# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "test" do |test|
      test.vm.hostname = "test"
      test.vm.network "private_network", ip: "172.20.20.10"
  end


  config.vm.provision "ansible" do |ansible|

    ansible.playbook = "test.yml"
    ansible.sudo = true
    ansible.verbose = true
  end
end